// Companies data + portfolio section
const COMPANIES = [
  {
    id: "international",
    n: "01",
    name: "Roba International",
    legal: "Pvt Ltd",
    region: "Maldives",
    role: "Trading & Distribution",
    short: "The flagship — distribution, trading, and lifestyle solutions.",
    blurb: "A dynamic trading and lifestyle solutions company delivering high-quality, convenience-driven products to modern markets. Distributors of Pasuda Foods Thailand and sales & marketing agent for KIMBO premium coffee through Citadel Pvt Ltd, supplying a curated range of premium Thai products.",
    capabilities: ["Distribution", "Trade & Brand Agency", "Sourcing", "Market Insight"],
    partners: ["Pasuda Foods (Thailand)", "KIMBO Premium Coffee", "Citadel Pvt Ltd"],
    website: "https://robainternational.com",
  },
  {
    id: "thailand",
    n: "02",
    name: "Roba International (Thailand)",
    legal: "Co., Ltd.",
    region: "Thailand",
    role: "Sourcing & Trade Hub",
    short: "Asia sourcing hub — supplier engagement, procurement, export.",
    blurb: "The group's Thailand-based sourcing and trade coordination hub. Positioned in one of Asia's key manufacturing and export centers, it focuses on identifying, consolidating, and supplying high-demand Thai and regional products for international markets.",
    capabilities: ["Supplier Engagement", "Procurement", "Export Handling", "Freight Forwarding"],
    partners: ["Maldives Markets", "Regional Buyers", "Thai Manufacturers"],
    website: "https://thailand.robainternational.com",
  },
  {
    id: "logistics",
    n: "03",
    name: "Roba Logistics & Handling",
    legal: "Pvt. Ltd.",
    region: "Maldives",
    role: "Logistics & Customs",
    short: "End-to-end customs brokerage, cargo handling, and clearance.",
    blurb: "A Maldives-based sister company specializing in end-to-end logistics solutions. We provide customs brokerage, cargo handling, and clearance services for goods arriving via both air and sea freight — from port to doorstep with fast, compliant, and reliable delivery.",
    capabilities: ["Customs Brokerage", "Cargo Handling", "Air & Sea Clearance", "Last-Mile Delivery"],
    partners: ["Maldives Customs", "Port Authorities", "Freight Carriers"],
    website: "https://logistics.robainternational.com",
  },
  {
    id: "media",
    n: "04",
    name: "Roba Media",
    legal: "Pvt. Ltd.",
    region: "Maldives",
    role: "Creative & Production",
    short: "Branding, content, digital marketing, visual storytelling.",
    blurb: "A creative and production-driven sister company focused on delivering impactful media and marketing solutions. We specialize in content creation, branding, digital marketing, and visual storytelling tailored for modern audiences — from concept to execution.",
    capabilities: ["Content Creation", "Branding", "Digital Marketing", "Visual Storytelling"],
    partners: ["Group Brands", "External Clients", "Production Partners"],
    website: "https://media.robainternational.com",
  },
  {
    id: "agri",
    n: "05",
    name: "Roba Agri-Marine Industries",
    legal: "Pvt Ltd",
    region: "Maldives",
    role: "Sustainability & Resource Recovery",
    short: "Organic inputs, eco-fertilizers, and resource recovery.",
    blurb: "A sustainability-focused sister company dedicated to transforming natural and organic resources into high-value agricultural and marine-based products. We convert materials such as coconut waste, seagrass, and fish by-products into practical, market-ready outputs.",
    capabilities: ["Organic Inputs", "Eco-Fertilizers", "Resource Recovery", "Marine By-products"],
    partners: ["Local Farmers", "Coconut Producers", "Fisheries"],
    website: "https://agrimarine.robainternational.com",
  },
  {
    id: "ceylon",
    n: "06",
    name: "Roba International Ceylon",
    legal: "Ltd.",
    region: "Sri Lanka",
    role: "Origin Sourcing & QA",
    short: "Direct sourcing at origin, supplier development, QA.",
    blurb: "The Sri Lanka-based sourcing and origin supply partner of the group, working closely with local producers, agricultural suppliers, and manufacturers to develop a reliable pipeline of export-ready goods. A ground-level sourcing and quality control extension.",
    capabilities: ["Origin Sourcing", "Supplier Development", "Quality Assurance", "Export Readiness"],
    partners: ["Ceylon Producers", "Tea Estates", "Agricultural Co-ops"],
    website: "https://ceylon.robainternational.com",
  },
];

window.COMPANIES = COMPANIES;
